# Generated by Django 3.0 on 2021-01-26 09:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues_Addressed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Regional_Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('number_of_staff', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('issues_addressed', models.ManyToManyField(blank=True, null=True, to='branches.Issues_Addressed')),
                ('regional_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Main_Office')),
            ],
        ),
        migrations.CreateModel(
            name='Field_Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_staff', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('field_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.Regional_Office')),
                ('issues_addressed', models.ManyToManyField(blank=True, null=True, to='branches.Issues_Addressed')),
            ],
        ),
    ]
