# Generated by Django 3.0 on 2021-01-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_counties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counties',
            name='codes',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='counties',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='cty_code',
        ),
        migrations.RemoveField(
            model_name='counties',
            name='dis',
        ),
        migrations.AddField(
            model_name='counties',
            name='const_code',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='constituen',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='county_cod',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='county_nam',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='id_field',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='objectid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='shape_area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='shape_leng',
            field=models.FloatField(null=True),
        ),
    ]
